# -*- coding: utf-8 -*-

# Dialog implementation generated from reading ui file 'imagedownUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from PyQt5.Qt import QFileSystemModel
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Download_Ui_Form:

    idhash_filename = ".\\IDHASH.bin"
    default_path = "NON"

    def __init__(self, Dialog):
        Dialog.resize(723, 200)
        Dialog.setWindowTitle("download tool")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(45)
        font.setBold(True)
        #self.groupBox.set(font)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 521, 131))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(450, 20, 61, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.on_cliked_event)
        self.lE_id_hash = QtWidgets.QLineEdit(self.groupBox)
        self.lE_id_hash.setGeometry(QtCore.QRect(110, 20, 331, 20))
        self.lE_id_hash.setObjectName("lE_id_hash")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 20, 91, 16))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 91, 16))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 91, 16))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 40, 331, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 60, 331, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(0, 80, 91, 16))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 80, 331, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 100, 331, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(0, 100, 91, 16))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.bt_run = QtWidgets.QPushButton(self.groupBox)
        self.bt_run.setGeometry(QtCore.QRect(450, 100, 61, 23))
        self.bt_run.setObjectName("bt_run")
        self.bt_run.clicked.connect(self.run_func)

        self.lE_id_hash.setText(self.load_hash())

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Android image download from artifact"))
        self.pushButton.setText(_translate("Dialog", "Save"))
        self.label.setText(_translate("Dialog", "ID Hash :"))
        self.label_2.setText(_translate("Dialog", "Target Path :"))
        self.label_3.setText(_translate("Dialog", "1st URL :"))
        self.label_4.setText(_translate("Dialog", "2nd URL :"))
        self.label_5.setText(_translate("Dialog", "Make CMD :"))
        self.bt_run.setText(_translate("Dialog", "RUN"))

    def on_cliked_event(self):
        print("bt test")
        self.save_hash()

    def save_hash(self):
        print("save_path ")
        f = open(self.idhash_filename, 'wr')
        #f.write(self.lE_id_hash.text())
        f.close()

    def load_hash(self):
        if os.path.isfile(self.idhash_filename):
            f = open(self.idhash_filename, 'r')
            self.temp_path = f.readline()
            #self.lE_id_hash.setText(self.temp_path)
            f.close()
        else:
            self.temp_path = self.default_path
        return self.temp_path

    def run_func(self):
        #curl - uyoungsoo.cho: APCrMdPFnN3M7K52eNCZdjEh5e - O
        #"http://art.lge.com/vc/aivi2/<TARGET_FILE_PATH>"
        #aivi2_ccc/FactoryOS/FactoryOS_image_release/newFacOS_Task/Factory_OS_Image_for_Concurrent_processing_FacOS_CORE_5.0_210402.zip
        default_curl = "curl -u"
        default_repository = "http://art.lge.com/vc/aivi2/"
        temp_cmd = default_curl + self.load_hash() + " -O " + default_repository + self.lineEdit_3.text()
        temp_cmd2 = default_curl + self.load_hash() + " -O " + self.lineEdit_2.text() + default_repository + self.lineEdit_4.text()
        print(temp_cmd + '\n' + temp_cmd2)
        os.system("d:")
        os.system("cd " + self.lineEdit_2.text())
        os.system("start cmd /k " + '\"'+temp_cmd+'\"')